### ISSUE TITLE
Make a simple way of getting the publish token for a box 

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/custard#153]
I'm accessing data in a box via the SQL API from an R script, so I use a line like this:

TwitterRecordsFile ='https://box.scraperwiki.com/g4cvcji/e8f75e2951344de/sql?q=select+*+from+twitter_followers'

It's fairly straightforward to get the box id (g4cvcji) but getting the public_token (e8f75e2951344de) was a bit tricky (I had to type Javascript into the Chrome console, under the supervision of an expert).

**Comment by StevenMaude** [comment]
For anyone reading — most likely me in the future — wondering *how* to get the publish_token from JavaScript as mentioned, what you want is:

```javascript
scraperwiki.readSettings().source['publishToken']
```
