### ISSUE TITLE
Half-broken view

### ISSUE THREAD

**Issue by frabcus** [scraperwiki/custard#610]
So to do this I clicked on "Summarize this data". Then I think, but I'm not sure, I went to another view again while it was still creating the Summarize tool. Certainly, I was impatient!

I then got a half complete dataset - it was a broken summarize that didn't work right.

Looking in custard log immediately, I think this was it:

```
checkThisIsMyDataHub POST /frabcus/datasets/qkiqy4r/views frabcus frabcus
server premium.scraperwiki.com boxName p7o0wzy
err:  425253889 undefined null
BOX CREATE posting to https://premium.scraperwiki.com/box/p7o0wzy
setDiskQuota on p7o0wzy error: null
```

Sorry for being vague - I can try and reproduce, but just wanted to capture it.

**Comment by pwaller** [comment]
Is this #674? I'm closing this one since it was a long time ago and the likelihood we can investigate this particular bug is small at this point.
