### ISSUE TITLE
FAQ when about up upgrade from free trial

### ISSUE THREAD

**Issue by frabcus** [scraperwiki/custard#617]
A customer just asked these questions:

* Can I use multiple Twitter accounts with one ScraperWiki account?
* My limit of 10 datasets, can I delete them and reuse the limit?
* Can I pay for you to write code to do more complicated things for me?

Not sure where to put this though, just tracking here for now.

**Comment by StevenMaude** [comment]
@frabcus Is this still an issue now signups are closed?
