### ISSUE TITLE
Password reset sends links that don't work

### ISSUE THREAD

**Issue by frabcus** [scraperwiki/custard#619]
I'm not sure what is happening here - I think after we've set up centralized logging search, we should have a look into it.

See this customer support thread: https://app.intercom.io/apps/63b0c6d4bb5f0867b6e93b0be9b569fb3a7ab1e3/conversations/385145790

**Comment by StevenMaude** [comment]
Was this some strange user-specific bug?

I don't recall seeing anyone else mention this as an issue via Intercom or email.
