### ISSUE TITLE
Navigation from application to blog / professional services

### ISSUE THREAD

**Issue by frabcus** [scraperwiki/custard#620]
The user need here, is that users can't find the blog or professional services while they are logged in.

This raises a bunch of questions.

[ ] Research other services like Xero, Recurly etc. do this, what works well in UX terms
[ ] Consider changing application to be on its down subdomain e.g. app.scraperwiki.com
[ ] Either add the navigation to the app, or whatever else is appropriate

**Comment by StevenMaude** [comment]
@frabcus Is this still an issue? Any users remaining after the current batch of free trials has expired will be paying us already.

**Comment by frabcus** [comment]
No, can be closed
