### ISSUE TITLE
Ghostery + optimizely prevents signup from working

### ISSUE THREAD

**Issue by pwaller** [scraperwiki/custard#706]
This is not an issue that we're necessarily going to fix, but I wanted to record it here so we can at least have a vague awareness of the problem.

A user complained that they clicked signup and it had no effect. It turned out that this happened because they had Ghostery installed which was blocking Optimizely.

Here is the description the user left:

```
I am trying to sign up for your free trial but it doesn't work. 

Once I click the "Create account" button it keeps on spinning indefinitely.
```

**Comment by StevenMaude** [comment]
There is no signup any more; closing.
