### ISSUE TITLE
"Sorry! We could not connect to the server" while trying to extract table from PDF

### ISSUE THREAD

**Issue by tsanislav** [scraperwiki/custard#723]
Hello,
In the past few days I have been trying to extract tables from PDF, but I keep getting the 'Sorry! We couldn't connect to the server, please try again.' error. 
![image](https://cloud.githubusercontent.com/assets/9040989/17206350/98808e76-54af-11e6-8314-60f930904ac1.png)
Thanks for helping me out!
Best regards,
Tsanislav Kolev

**Comment by frabcus** [comment]
Hi!

To convert PDFs now, please go to https://pdftables.com/

Thanks!
